version: "3"
services:
  scheduler:
    image: arinarmo/dask-node:latest
    entrypoint: dask-scheduler
    ports:
      - 8786:8786
      - 8787:8787
      - 8788:8788
      - 8789:8789
    volumes:
      - ./data:/data

  worker:
    image: arinarmo/dask-node:latest
    entrypoint: dask-worker scheduler:8786
    volumes:
      - ./data:/data

  notebook:
    image: arinarmo/daskintro_notebook:latest
    entrypoint: jupyter notebook
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jupyter/workspace/notebooks
      - ./data:/data
